### ISSUE TITLE
Restart the service during a refresh 

### ISSUE THREAD

**Issue by jonathanudd** [dwellir-public/snap-polkadot#17]
We need to restart the service during a refresh since it there might be changes that requires a restart e.g. a new binary.

It's probably enough to restart it in the post refresh hook to have as low downtime as possible.

**Comment by erik78se** [comment]
If the node is a validator, it must not be restarted since it might lose
its spot in the so called active set.

Den tis 24 okt. 2023 09:54Jonathan Udd ***@***.***> skrev:

**Comment by erik78se** [comment]
Hmm. Good question...

Let's work something out.

Den tis 24 okt. 2023 13:38Jonathan Udd ***@***.***> skrev:
